kind: Service
apiVersion: v1
metadata:
  name: kibana
  labels:
    name: kibana
    deployment: {{ DEPLOY_TO }}
spec:
  type: NodePort
  ports:
  - name: kibana
    port: {{ KIBANA_SERVICE_PORT }}
    nodePort: {{ KIBANA_SERVICE_PORT }}
  selector:
    name: kibana
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kibana
        deployment: {{ DEPLOY_TO }}
    spec:
      containers:
      - name: kibana-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/kibana:{{ TIMESTAMP }}
        ports:
        - containerPort: {{ KIBANA_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: IfNotPresent
        env:
        - name: KIBANA_SERVICE_PORT
          value: "{{ KIBANA_SERVICE_PORT }}"
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "{{ ELASTICSEARCH_SERVICE_PORT }}"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
